#这个也是一个配置文件，启动后端时去执行application.module()，监听8080端口，链接本地H2数据库，数据库对象名转成小写
ktor:
    application:
        modules:
            - com.example.ApplicationKt.module
    deployment:
        port: 8080

db:
  url: "jdbc:h2:file:./data/fitness;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE"

  driver: "org.h2.Driver"
  user: "sa"
  password: ""

auth:
  tokenTtlHours: 168
seed:
  adminEmail: "admin@example.com"
  adminPassword: "admin"